### ISSUE TITLE
精简css的内容

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/examples#65]
因css不是example的主要内容
将css中的空格去掉, 把每个css class定义缩减为一行

例如将

```css
    html,
    body {
        margin: 0px;
        height: 100%;
        width: 100%;
    }

    #map {
        width: 100%;
        height: 100%;
    }
```

改为:

```css
    html, body { margin: 0px; height: 100%; width: 100%;}
    #map { width: 100%; height: 100%; }
```
